**DEA - Main Dataset**

In [50]:
!pip install pulp
import pulp
!apt-get install -y -qq glpk-utils
from pulp import GLPK
import pandas as pd
import numpy as np

data = pd.read_csv("/content/DEA_Main.csv")

weights_matrix = np.empty((14,9))
for k in range(9):
    dea_model = pulp.LpProblem("F1_Analysis", pulp.LpMaximize)
    m1 = pulp.LpVariable("m1", lowBound=0, upBound=None, cat='Continuous')
    m2 = pulp.LpVariable("m2", lowBound=0, upBound=None, cat='Continuous')
    m3 = pulp.LpVariable("m3", lowBound=0, upBound=None, cat='Continuous')
    m4 = pulp.LpVariable("m4", lowBound=0, upBound=None, cat='Continuous')
    m5 = pulp.LpVariable("m5", lowBound=0, upBound=None, cat='Continuous')
    m6 = pulp.LpVariable("m6", lowBound=0, upBound=None, cat='Continuous')
    n1 = pulp.LpVariable("n1", lowBound=0, upBound=None, cat='Continuous')
    n2 = pulp.LpVariable("n2", lowBound=0, upBound=None, cat='Continuous')
    n3 = pulp.LpVariable("n3", lowBound=0, upBound=None, cat='Continuous')
    n4 = pulp.LpVariable("n4", lowBound=0, upBound=None, cat='Continuous')
    n5 = pulp.LpVariable("n5", lowBound=0, upBound=None, cat='Continuous')
    n6 = pulp.LpVariable("n6", lowBound=0, upBound=None, cat='Continuous')
    n7 = pulp.LpVariable("n7", lowBound=0, upBound=None, cat='Continuous')
    n8 = pulp.LpVariable("n8", lowBound=0, upBound=None, cat='Continuous')

    dea_model += m1*data["Y1"][k] + m2*data["Y2"][k] + m3*data["Y3"][k] + m4*data["Y4"][k] + m5*data["Y5"][k] + m6*data["Y6"][k]

    dea_model += n1*data["X1"][k] + n2*data["X2"][k] + n3*data["X3"][k] + n4*data["X4"][k] + n5*data["X5"][k] + n6*data["X6"][k] + n7*data["X7"][k] + n8*data["X8"][k] == 1

    for i in range(9):
        dea_model += m1*data["Y1"][i] + m2*data["Y2"][i] + m3*data["Y3"][i] + m4*data["Y4"][i] + m5*data["Y5"][i] + m6*data["Y6"][i] - n1*data["X1"][i] - n2*data["X2"][i] - n3*data["X3"][i] - n4*data["X4"][i] - n5*data["X5"][i] - n6*data["X6"][i] - n7*data["X7"][i] - n8*data["X8"][i] <= 0

    status = dea_model.solve()
    print("Model Status:{}".format(pulp.LpStatus[dea_model.status]))

    list_weights=[]
    for v in dea_model.variables():
	      print(v.name, "=", v.varValue)
    for v in dea_model.variables():
        list_weights = list_weights + [v.varValue]
    for n in range(14):
        value = list_weights[n]
        weights_matrix[n,k] = value

    print("Objective=", pulp.value(dea_model.objective))

    print("\nConstraint")
    for name, c in dea_model.constraints.items():
	      print(name, ":", c)

Model Status:Optimal
m1 = 0.0
m2 = 0.097570602
m3 = 0.0
m4 = 0.036755543
m5 = 0.0
m6 = 0.15775578
n1 = 0.0
n2 = 0.0
n3 = 0.0095864516
n4 = 0.0
n5 = 0.0058778258
n6 = 0.0
n7 = 0.0
n8 = 0.0
Objective= 0.9999999985000001

Constraint
_C1 : 190*n1 + 380*n2 + 43*n3 + 22*n4 + 100*n5 + 1.099*n6 + 1000*n7 + 8*n8 = 1.0
_C2 : 8*m2 + 409*m3 + 2*m4 + 5*m5 + 0.925*m6 - 190*n1 - 380*n2 - 43*n3 - 22*n4 - 100*n5 - 1.099*n6 - 1000*n7 - 8*n8 <= -0.0
_C3 : 21*m1 + 30*m2 + 860*m3 + 20*m4 + 11*m5 + 0.967*m6 - 180*n1 - 380*n2 - 65*n3 - 25*n4 - 543*n5 - n6 - 1040*n7 - 10*n8 <= -0.0
_C4 : m1 + 9*m2 + 406*m3 + 2*m4 + 0.894*m6 - 180*n1 - 375*n2 - 36*n3 - 23*n4 - 468*n5 - 1.316*n6 - 1050*n7 - 6*n8 <= -0.0
_C5 : 9*m2 + 302*m3 + m4 + 3*m5 + 0.912*m6 - 160*n1 - 320*n2 - 22*n3 - 22*n4 - 418*n5 - 1.064*n6 - 1000*n7 - 6*n8 <= -0.0
_C6 : 8*m2 + 280*m3 + m5 + 0.88*m6 - 150*n1 - 260*n2 - 7*n3 - 23*n4 - 145*n5 - 1.087*n6 - 740*n7 - 10*n8 <= -0.0
_C7 : 2*m2 + 120*m3 + 0.93*m6 - 140*n1 - 240*n2 - 11*n3 - 22*n4 - 191*n5 - 1.1

In [51]:
weights_matrix

array([[0.0000000e+00, 0.0000000e+00, 2.7353641e-02, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [9.7570602e-02, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        9.3509181e-06, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 9.5454796e-05, 2.3339290e-05,
        0.0000000e+00, 4.1896302e-04, 4.4770475e-03, 2.6156007e-03,
        5.4859869e-03],
       [3.6755543e-02, 5.0000000e-02, 0.0000000e+00, 2.9532798e-02,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 4.4019609e-03,
        5.7106242e-01, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        2.7628702e-02],
       [1.5775578e-01, 0.0000000e+00, 1.0446216e+00, 1.0419001e+00,
        4.8734406e-01, 9.3915295e-01, 6.2194346e-01, 1.0228224e+00,
        8.7457762e-01],
       [0.0000000e+00, 0.0000000e+00, 0.

**Cross Efficiency & Arithmetic Cross-efficiency**

In [53]:
from statistics import mean
import pandas as pd

cross_efficiency_table = np.empty((9,9))
avg_efficiency = []
for row in range(9):
    row_values = []
    for column in range(9):
        value = ((weights_matrix[0,column]*data["Y1"][row])+(weights_matrix[1,column]*data["Y2"][row])+(weights_matrix[2,column]*data["Y3"][row])+(weights_matrix[3,column]*data["Y4"][row])+(weights_matrix[4,column]*data["Y5"][row])+(weights_matrix[5,column]*data["Y6"][row]))/((weights_matrix[6,column]*data["X1"][row])+(weights_matrix[7,column]*data["X2"][row])+(weights_matrix[8,column]*data["X3"][row])+(weights_matrix[9,column]*data["X4"][row])+(weights_matrix[10,column]*data["X5"][row])+(weights_matrix[11,column]*data["X6"][row])+(weights_matrix[12,column]*data["X7"][row])+(weights_matrix[13,column]*data["X8"][row]))
        cross_efficiency_table[row,column] = value
        row_values += [value]
    average = mean(row_values)
    avg_efficiency += [average]

average_list_rounded = [ '%.3f' % elem for elem in avg_efficiency ]

F1_Teams = data['F1-Team'].tolist()

for team in F1_Teams:
    index = F1_Teams.index(team)
    print("Arithmetic Cross-efficiency score for",team,"=",average_list_rounded[index])

F1_cross_efficiency = cross_efficiency_table.round(decimals=2)

F1_cross_efficiency_table = pd.DataFrame(F1_cross_efficiency)
F1_cross_efficiency_table.insert(0, 'F1-Teams', F1_Teams)
set_column_names = ['F1-Teams'] + [team + " weight" for team in F1_Teams]
F1_cross_efficiency_table.columns = set_column_names

display(F1_cross_efficiency_table)

F1_cross_efficiency_table.to_csv("Cross_Eff_DEA_Result.csv", index=False)

Arithmetic Cross-efficiency score for Mercedes = 0.758
Arithmetic Cross-efficiency score for Red Bull = 0.879
Arithmetic Cross-efficiency score for Ferrari = 0.555
Arithmetic Cross-efficiency score for McLaren = 0.637
Arithmetic Cross-efficiency score for Aston Martin = 0.764
Arithmetic Cross-efficiency score for Alpine = 0.533
Arithmetic Cross-efficiency score for Williams = 0.831
Arithmetic Cross-efficiency score for Haas = 0.731
Arithmetic Cross-efficiency score for AlphaTauri = 0.666


F1-Teams  Mercedes weight  Red Bull weight  Ferrari weight  \
0      Mercedes             1.00             0.15            0.75   
1      Red Bull             1.00             1.00            1.00   
2       Ferrari             0.35             0.18            1.00   
3       McLaren             0.40             0.15            0.98   
4  Aston Martin             1.00             0.00            0.57   
5        Alpine             0.28             0.00            0.84   
6      Williams             0.75             0.00            0.87   
7          Haas             1.00             0.00            0.85   
8    AlphaTauri             0.10             0.00            1.00   

   McLaren weight  Aston Martin weight  Alpine weight  Williams weight  \
0            0.79                 0.91           1.00             1.00   
1            1.00                 1.00           0.90             1.00   
2            1.00                 0.10           0.96             0.63   
3            1.00                 0.71           1.00             0.60   
4            0.56                 1.00           0.75             1.00   
5            0.83                 0.31           0.92             0.57   
6            0.86                 1.00           1.00             1.00   
7            0.85                 0.79           1.00             0.72   
8            1.00                 1.00           1.00             0.39   

   Haas weight  AlphaTauri weight  
0         1.00               0.22  
1         0.74               0.27  
2         0.52               0.25  
3         0.55               0.35  
4         1.00               1.00  
5         0.64               0.40  
6         1.00               1.00  
7         1.00               0.38  
8         0.51               1.00

**GEOMETRIC MEAN EFFICIENCY**

In [54]:
import math
import numpy as np

# Convert to a numpy array for convenience
matrix = np.array(F1_cross_efficiency)

# Fixing the zero efficiency score
matrix[4,1] = 1e-6
matrix[5,1] = 1e-6
matrix[6,1] = 1e-6
matrix[7,1] = 1e-6
matrix[8,1] = 1e-6

# Compute geometric mean for each DMU (rows)
geometric_means = [math.prod(matrix[i, :]) ** (1 / matrix.shape[1]) for i in range(matrix.shape[0])]

# Display results
for dmu, gm in enumerate(geometric_means, start=0):
    team_name = F1_Teams[dmu]
    print(f"Geometric Mean efficiency for {team_name}: {round(gm, 3):.3f}")

Geometric Mean efficiency for Mercedes: 0.639
Geometric Mean efficiency for Red Bull: 0.826
Geometric Mean efficiency for Ferrari: 0.429
Geometric Mean efficiency for McLaren: 0.553
Geometric Mean efficiency for Aston Martin: 0.184
Geometric Mean efficiency for Alpine: 0.126
Geometric Mean efficiency for Williams: 0.202
Geometric Mean efficiency for Haas: 0.175
Geometric Mean efficiency for AlphaTauri: 0.139


**CEC REFER TO PAPER**

In [55]:
F1_cross_efficiency

array([[1.  , 0.15, 0.75, 0.79, 0.91, 1.  , 1.  , 1.  , 0.22],
       [1.  , 1.  , 1.  , 1.  , 1.  , 0.9 , 1.  , 0.74, 0.27],
       [0.35, 0.18, 1.  , 1.  , 0.1 , 0.96, 0.63, 0.52, 0.25],
       [0.4 , 0.15, 0.98, 1.  , 0.71, 1.  , 0.6 , 0.55, 0.35],
       [1.  , 0.  , 0.57, 0.56, 1.  , 0.75, 1.  , 1.  , 1.  ],
       [0.28, 0.  , 0.84, 0.83, 0.31, 0.92, 0.57, 0.64, 0.4 ],
       [0.75, 0.  , 0.87, 0.86, 1.  , 1.  , 1.  , 1.  , 1.  ],
       [1.  , 0.  , 0.85, 0.85, 0.79, 1.  , 0.72, 1.  , 0.38],
       [0.1 , 0.  , 1.  , 1.  , 1.  , 1.  , 0.39, 0.51, 1.  ]])

In [56]:
# Get the second row
CRP_DMU = F1_cross_efficiency[1]

# Create a new array and divide each column by the corresponding value of CRP-DMU
Rescale_Matrix = np.zeros_like(F1_cross_efficiency)
for i in range(F1_cross_efficiency.shape[1]):
    Rescale_Matrix[:, i] = F1_cross_efficiency[:, i] / CRP_DMU[i]

Rescale_Matrix = np.round(Rescale_Matrix, 2)

Rescale_Matrix

array([[1.  , 0.15, 0.75, 0.79, 0.91, 1.11, 1.  , 1.35, 0.81],
       [1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ],
       [0.35, 0.18, 1.  , 1.  , 0.1 , 1.07, 0.63, 0.7 , 0.93],
       [0.4 , 0.15, 0.98, 1.  , 0.71, 1.11, 0.6 , 0.74, 1.3 ],
       [1.  , 0.  , 0.57, 0.56, 1.  , 0.83, 1.  , 1.35, 3.7 ],
       [0.28, 0.  , 0.84, 0.83, 0.31, 1.02, 0.57, 0.86, 1.48],
       [0.75, 0.  , 0.87, 0.86, 1.  , 1.11, 1.  , 1.35, 3.7 ],
       [1.  , 0.  , 0.85, 0.85, 0.79, 1.11, 0.72, 1.35, 1.41],
       [0.1 , 0.  , 1.  , 1.  , 1.  , 1.11, 0.39, 0.69, 3.7 ]])

In [57]:
import math

# Fixing the value of zero
Rescale_Matrix[4,1] = 1e-6
Rescale_Matrix[5,1] = 1e-6
Rescale_Matrix[6,1] = 1e-6
Rescale_Matrix[7,1] = 1e-6
Rescale_Matrix[8,1] = 1e-6

# Compute geometric mean for each DMU (rows)
geometric_mean = [math.prod(Rescale_Matrix[i, :]) ** (1 / Rescale_Matrix.shape[1]) for i in range(Rescale_Matrix.shape[0])]

# Initialize sum_squared as a list to store the values
root_sum_squared_list = []

# Iterate over each column
for col in range(Rescale_Matrix.shape[1]):
  column = Rescale_Matrix[:, col]  # Select the current column
  mean = geometric_mean[col]  # Access corresponding geometric mean

  # Calculate square root of squared deviations and sum
  deviations = math.sqrt(sum((x - mean)**2 for x in column))

  # Append the root of sum of squared deviations for the column
  root_sum_squared_list.append(deviations)

# Convert the string values to float
root_sum_squared_list = [float(x) for x in root_sum_squared_list]

root_sum_squared_list

[1.1045261831810997,
 2.667843698571001,
 1.1375489616756953,
 0.7489467053358358,
 1.8642452774320901,
 2.7119351368547777,
 1.7065340771480157,
 2.6391468615731637,
 6.605540594896817]

In [58]:
# Calculate 1/(1+x) for each value
ECD = [1 / (1 + x) for x in root_sum_squared_list]

ECD

[0.4751663381485939,
 0.27263975299427345,
 0.4678255412760543,
 0.5717727115120859,
 0.34913211095403807,
 0.26940125921686414,
 0.3694762273430307,
 0.27478967957003825,
 0.1314830928219596]

In [59]:
import numpy as np

# Calculate the sum of all powers
total_power = sum(ECD)

# Calculate the product of each row, raised to the power of the total power
CEC_Results = []
for i in range(len(ECD)):
  row = Rescale_Matrix[i]
  product = np.prod(np.power(row, ECD[i]))
  result = np.power(product, 1/total_power)
  CEC_Results.append(result)

CEC_Results = np.array(CEC_Results)  # Convert to NumPy array
CEC_Results = CEC_Results.round(decimals=2)

for team in F1_Teams:
    index = F1_Teams.index(team)
    print("CEC score for",team,"=",CEC_Results[index])

CEC score for Mercedes = 0.71
CEC score for Red Bull = 1.0
CEC score for Ferrari = 0.42
CEC score for McLaren = 0.52
CEC score for Aston Martin = 0.23
CEC score for Alpine = 0.24
CEC score for Williams = 0.23
CEC score for Haas = 0.3
CEC score for AlphaTauri = 0.52
